AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stack that creates a Lambda function

Resources:

  getFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: dotnetcore2.1
      Handler: aws-lambda-test::aws_lambda_test.Function::FunctionHandler
      CodeUri: s3://aws-lambda-test-1/aws-lambda-test.zip
      Environment:
        Variables:
          QUEUENAME: !ImportValue awsWsQueueName
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /appveyor
            Method: GET
